
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MATHEMATICAL_OPERATOR = 8;
  public static final int DEFINE = 2;
  public static final int RELATIONAL_OPERATOR = 7;
  public static final int BOOLEAN_LITERAL = 6;
  public static final int DISPLAY = 5;
  public static final int STRING_LITERAL = 13;
  public static final int EOF = 0;
  public static final int IF = 3;
  public static final int FLOAT_LITERAL = 15;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int IDENTIFIER = 12;
  public static final int NEW_LINE = 9;
  public static final int LPAREN = 10;
  public static final int DO = 4;
  public static final int INTEGER_LITERAL = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINE",
  "IF",
  "DO",
  "DISPLAY",
  "BOOLEAN_LITERAL",
  "RELATIONAL_OPERATOR",
  "MATHEMATICAL_OPERATOR",
  "NEW_LINE",
  "LPAREN",
  "RPAREN",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL"
  };
}

