# Generated by Django 3.0.5 on 2020-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablechart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpart',
            name='comments',
            field=models.CharField(max_length=200, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='chartpart',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='chartpart',
            name='end',
            field=models.TimeField(verbose_name='ساعت پایان کلاس'),
        ),
        migrations.AlterField(
            model_name='chartpart',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='chartpart',
            name='professor',
            field=models.CharField(max_length=100, verbose_name='نام استاد یا ارائه دهنده'),
        ),
        migrations.AlterField(
            model_name='chartpart',
            name='start',
            field=models.TimeField(verbose_name='ساعت شروع کلاس'),
        ),
    ]
