# Generated by Django 3.0.5 on 2020-04-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablechart', '0002_auto_20200419_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpart',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='روز'),
        ),
    ]
