# Generated by Django 3.0.5 on 2020-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablechart', '0003_auto_20200420_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpart',
            name='day',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'يکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنج شنبه')], verbose_name='روز'),
        ),
    ]
